# Generated by Django 5.1.7 on 2025-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('organizers', 'Organizers'), ('admin', 'Admin')], max_length=10, verbose_name='User type'),
        ),
    ]
