# Generated by Django 5.1.7 on 2025-04-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_event_organizerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='stage_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Stage name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='company_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Company name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
